### ISSUE TITLE
Does not build for windows on linux machine.

### ISSUE THREAD

**Issue by mayank7533** [sqweek/dialog#16]
Gives error message
/github.com/AllenDang/w32/user32.go:1039: cannot use flag (type uint32) as type uintptr in argument to procRedrawWindow.Call

**Comment by sqweek** [comment]
Note this is reported upstream as AllenDang/w32#80 - there's a suggested fix there too.

**Comment by sqweek** [comment]
The problem was introduced quite recently it seems; if you checkout 7bbaa2bee74 from AllenDang/w32 in your local go/src tree that should also workaround the problem until it's fixed properly.

Let me know if that doesn't work, I've never tried to cross compile go and would love to hear how it goes :)

**Comment by mayank7533** [comment]
solved the issue by implementing your workaround in https://github.com/mayank7533/dialog . You might consider accepting my merge request.
